#! /usr/bin/env python
# encoding: utf-8

import shutil, subprocess, os

def options(opt):
    pass

def configure(conf):
    PLINGELING = conf.path.abspath() + '/plingeling'
    shutil.rmtree(PLINGELING, True)
    subprocess.check_call(['git', 'clone', 'https://github.com/arminbiere/lingeling.git', PLINGELING]);

def build(bld):

    def shmake(task):
        src = task.inputs[0].abspath()
        tgt = task.outputs[0].abspath()
        subprocess.check_call('cd ' + os.path.dirname(src) +
                              ' && ./' + os.path.basename(src) +
                              ' && make plingeling', shell=True)
        subprocess.check_call(['mv', os.path.dirname(src) + '/plingeling', tgt])
        return 0
        
    bld(rule = shmake,
        source = 'plingeling/configure.sh',
        target = 'plingeling')
    
    bld.install_files('${LIBDIR}', 'plingeling', chmod=755)

def distclean(ctx):
    from waflib import Scripting
    Scripting.distclean(ctx)
    shutil.rmtree(ctx.path.abspath() + '/plingeling', True)

