#! /usr/bin/env python
# encoding: utf-8

import shutil
import subprocess

def options(opt):
    opt.load('compiler_c')
    opt.load('java')

def configure(conf):
    conf.load('compiler_c')
    conf.load('java')
    conf.check_jni_headers()
    LINGELING = conf.path.abspath() + '/lingeling'
    shutil.rmtree(LINGELING, True)
    subprocess.check_call(['git', 'clone', 'https://github.com/arminbiere/lingeling.git', LINGELING])

def build(bld):
    DEFINES = ['NLGLOG', 'NDEBUG', 'NCHKSOL', 'NLGLDRUPLIG', 'NLGLYALSAT', 'LGLFILES', 'NLGLDEMA']
    CFLAGS = ['-w', '-O3', '-fPIC']
    INCLUDES = ['.', './lingeling']
    
    bld.objects(source = ['lingeling/lglib.c', 'lingeling/lglopts.c'],
                target = 'lglib',
                includes = INCLUDES, cflags = CFLAGS, defines = DEFINES)
    
    bld.shlib(source = 'kodkod_engine_satlab_Lingeling.c',
              target = 'lingeling',
              use = 'lglib', uselib = 'JAVA',
              includes = INCLUDES, cflags = CFLAGS, defines = DEFINES)

def distclean(ctx):
    from waflib import Scripting
    Scripting.distclean(ctx)
    shutil.rmtree(ctx.path.abspath() + '/lingeling', True)

